<?php
/**
 * Generated by framework installer - Mon, 14 Nov 2016 15:24:31 +0100
*/
    class Config
    {
	const BASEDNAME	= '/webproject';
	const DBHOST	= 'localhost';
	const DB	= 'webproject';
	const DBUSER	= 'webproject';
	const DBPW	= 'webproject';
	const SITENAME	= 'webproject';
	const SITEURL	= 'http://eddy.com';
	const SITENOREPLY	= 'eddybrown@me.com';
	const SYSADMIN	= 'eddybrown@me.com';
	const DBOP	= '=';
	const UPUBLIC	= FALSE;
	const UPRIVATE	= TRUE;

	public static function setup()
	{
	    Web::getinstance()->addheader([
		'Date'			=> gmstrftime('%b %d %Y %H:%M:%S', time()),
		'Window-target'		=> '_top',	# deframes things
		'X-Frame-Options'	=> 'DENY',	# deframes things
		'Content-Language'	=> 'en',
		'Vary'			=> 'Accept-Encoding',
	    ]);
	}
    }
?>
